### ISSUE TITLE
Strikethrough formatting not exported

### ISSUE THREAD

**Issue by sweenzor** [bshannon/savenotes#3]
Text with strikethrough formatting is not exported to markdown

For example, this text results in unadorned text in the output 
> ~~example~~

becomes 
> example

Suggest using the [GFM format](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for strikethrough export
`~~example~~`

**Comment by bshannon** [comment]
Fixing this was fairly easy, but my testing of the fix pointed out another problem.
There doesn't seem to be a consistent way to force a line break in text.  The code
currently adds a backslash at the end of a line to force a line break because that
works with GitHub Flavored Markdown, but it doesn't work with some others.

**Comment by sweenzor** [comment]
Thanks, I'll keep an eye out for any unwanted line break behavior. Haven't
noticed any yet.
